PUT http://127.0.0.1:3000/movies?id=4 HTTP/1.1
content-type: application/json

{
  "title": "Castelo Animado",
  "source": "http://casteloanimado.com/casteloanimado.mp4",
  "description": "Um filme que um bixinho de fogo muito simpáticpo",
  "thumb": "http://casteloanimado.com/casteloanimado.jpg"
}