PUT https://ismaelmello-miniature-eureka-5979prjj6wxc9x4-3000.preview.app.github.dev/ HTTP/1.1
content-type: application/json

{
  "title": "Castelo Animado",
  "source": "http://alksdfjlsadfjlskad.com/akudhaskduas.mp4",
  "description": "Um filme que um bixinho de fogo muito sim[pát]icpo",
  "thumb": "http://alksdfjlsadfjlskad.com/akudhaskduas.jpg"
}